@startuml
title Διάγραμμα Δραστηριότητας - Επίδομα Πετρελαίου Θέρμανσης

skinparam backgroundColor #FFFFFF
skinparam activityFontSize 11
skinparam activityArrowFontSize 10

start

:Δικαιούχος υποβάλλει
ηλεκτρονική αίτηση;

:Καταχώριση στοιχείων:
- ΑΦΜ
- Αριθμός τραπεζικού λογαριασμού
- Συνολική δαπάνη πετρελαίου
- Αριθμός παροχής ρεύματος;

:Έλεγχος εγκυρότητας ΑΦΜ;

if (ΑΦΜ έγκυρο;) then (ΟΧΙ)
  :Αποστολή email απόρριψης
  (Μη έγκυρο ΑΦΜ);
  stop
else (ΝΑΙ)
  :Έλεγχος εισοδήματος
  προηγούμενου έτους;

  if (Εισόδημα ≤ 20.000€;) then (ΟΧΙ)
    :Αποστολή email απόρριψης
    (Υπέρβαση ορίου εισοδήματος);
    stop
  else (ΝΑΙ)
    :Έλεγχος προηγούμενης
    αίτησης τρέχοντος έτους;

    if (Έχει υποβάλει άλλη αίτηση;) then (ΝΑΙ)
      :Αποστολή email απόρριψης
      (Υπάρχει ήδη αίτηση);
      stop
    else (ΟΧΙ)
      :Έλεγχος εγκυρότητας
      αριθμού παροχής ρεύματος;

      if (Αριθμός παροχής έγκυρος;) then (ΟΧΙ)
        :Αποστολή email απόρριψης
        (Μη έγκυρος αριθμός παροχής);
        stop
      else (ΝΑΙ)
        :Έγκριση αίτησης;

        :Καταβολή επιδόματος;

        :Ενημέρωση τραπεζικού
        λογαριασμού δικαιούχου;

        :Αποστολή email επιβεβαίωσης;

        stop
      endif
    endif
  endif
endif

@enduml
